### ISSUE TITLE
Website not loading on Firefox v76.0 

### ISSUE THREAD

**Issue by trevancrowe** [tari-project/tari-dot-com-old#1] opened 2020-05-06 21:25 UTC
A member of the Tari community mentioned they are not able to get tari.com to load on the latest version of firefox. Could not reproduce on my end, might need some additional testing to determine the root of the cause. 

![image](https://user-images.githubusercontent.com/8609983/81229769-9929f780-8fad-11ea-9275-1cb5dbe6bf3e.png)

**Comment by CjS77** [comment] 2020-07-16 12:03
Can't reproduce on FF v77.0.1

**Comment by CjS77** [comment] 2020-07-16 15:01
Assuming the issue is resolved. Please re-open if it resurfaces.

**Comment by delta1** [comment] 2020-09-07 06:40
Hey @CjS77 @trevancrowe could we please reopen this issue? It happens pretty reliably for me on the latest FF (80.0.1) on Windows 10, specifically on the downloads page. 

It appears that the content is loaded, but for some reason the `animsition` class doesn't get removed from the viewport div. 

I am going to try reproduce on localhost and hopefully submit a PR. 

It could be related to: 
* https://github.com/blivesta/animsition/issues/150 
* https://github.com/blivesta/animsition/issues/95#issuecomment-200187015 

![](https://i.imgur.com/2VN9osZ.png)

**Comment by delta1** [comment] 2020-09-08 06:55
With #42 merged I think this is resolved now!

**Closed as completed** 2020-09-08 07:27 UTC
